[target.thumbv7m-none-eabi]
runner = "qemu-system-arm -cpu cortex-m3 -machine lm3s6965evb -nographic -semihosting-config enable=on,target=native -kernel"
rustflags = [
  "-C", "link-arg=-Tlink.ld",
  "-C", "link-arg=-Tlog.ld",
]

[build]
target = "thumbv7m-none-eabi"